
<section class = "compte">
    <h1 class = "moulaga"><?= $data["group"]->getBudget() ." $" ?></h1>

    <?php $code_groupe = $data["group"]->getCode(); ?>
    <div class = "add">
        <form method="POST" action="index.php?route=budget/ajouter">
            <h2>Ajouter un montant au budget</h2>
            
            <input type="number" step="0.01" name="montant_ajout" id="montant_ajout" placeholder="Montant à ajouter" required>
            
            <input type="hidden" name="code_groupe" value="<?php echo $code_groupe; ?>">
            
            <button type="submit">Ajouter</button>
        </form>
    </div>
    <?php $code_groupe = $data["group"]->getCode();?>

    <div class = "sub">
        <form method="POST" action="index.php?route=budget/retirer">
            <h2>Retirer un montant du budget</h2>
            
            <input type="number" step="0.01" name="montant_retrait" id="montant_retrait" placeholder="Montant à retirer"  required >
            
            <input type="hidden" name="code_groupe" value="<?php echo $code_groupe; ?>">
            
            <button type="submit">Retirer</button>
        </form>
    </div>
    <a class ="ajou" href="?route=depense/creer&code=<?php echo htmlspecialchars($code_groupe); ?>"> Crée depance </a>
    <a class ="voir"href="?route=depense/liste&code_groupe=<?php echo htmlspecialchars($code_groupe); ?>"> Voir toutes les dépenses </a>
</section>