<div class="login">
    
    <h2 class="titr">Connexion</h2>
    
    <?php 
    if (isset($error) && $error){
    ?>
        <div class="alert alert-danger"><?= htmlspecialchars($error) ?></div>
    <?php } ?>
    
    <form method="POST" action="index.php?route=login">

    <label for="email">Email</label>
    <input type="email" name="email" id="email" required>

    <label for="password">Mot de passe</label>
    <input type="password" name="password" id="password" required>

    <button type="submit">Se connecter</button>

</form>
    <p class="mt-3">Pas encore de compte ? <a href="?route=inscription">Créer un compte</a></p>

</div>